### ISSUE TITLE
Japanese Translation Progress Checklist

### ISSUE THREAD

**Issue by minaminao** [solidity-docs/ja-japanese#1]
### Maintainer List

@minaminao @JohannesMDr

### For Maintainers

When someone likes to contribute, edit this issue with the username of the contributor, and with the PR. 

E.g. 
- [ ] index (@franzihei) #1

When PRs are merged, make sure to mark that page as completed.

### Core Pages

These pages need to be translated before the translation will be added as a new language to the Solidity docs flyout menu. Please translate these pages first. 

#### Basics
- [ ] index
- [ ] intro-to-smart-contracts
- [ ] installing-solidity
- [ ] solidity-by-example

#### Language Description
- [ ] layout-of-source-files
- [ ] structure-of-a-contract
- [ ] types
- [ ] units-and-global-variables
- [ ] control-structures
- [ ] contracts
- [ ] assembly
- [ ] cheatsheet
- [ ] grammar

#### Internals
- [ ] layout_in_storage
- [ ] layout_in_memory
- [ ] layout_in_calldata
- [ ] variable_cleanup
- [ ] source_mappings
- [ ] optimiser
- [ ] metadata
- [ ] abi-spec

#### Additional Material
- [ ] yul
- [ ] natspec-format
- [ ] security-considerations
- [ ] common-patterns

### Next Steps

These are the next most important translations, ordered by importance:

#### Additional Material

- [ ] using-the-compiler
- [ ] contributing
- [ ] 080-breaking-changes
- [ ] 070-breaking-changes
- [ ] 060-breaking-changes
- [ ] 050-breaking-changes
- [ ] resources
- [ ] bugs

### Additional Translations

These are not the primary translation targets but still a nice to have!

- [ ] style-guide
- [ ] brand-guide

_Credits: This doc is derived from the [Progress Template](https://github.com/reactjs/reactjs.org-translation/blob/master/PROGRESS.template.md) of the ReactJS Localization Team._
